[Перейти на сайт](https://ru.hexlet.io)

# Как читать вывод тестов в Go

Чтобы вам было проще разобраться в выводе тестов, в первую очередь объясним, как работают тесты на платформе.

Тестирование кода на Go происходит с помощью [фреймворка Testify](https://github.com/stretchr/testify/), сами тесты также написаны на языке Go. Проверка кода запускается автоматически после нажатия на кнопку «Проверить». Тестируемая программа компилируется и проверяется с разными входными данными. При этом тесты следят, чтобы поведение программы соответствовало ожиданиям.

Когда тесты завершатся, на вкладке OUTPUT появится результат проверки. Если на этом этапе возникла ошибка, нужно прочитать вывод тестов. Этот вывод — наш главный помощник в отладке кода.

# Виды ошибок

Никто не пишет код идеально. Поэтому рано или поздно вы столкнетесь с ошибками. Ошибки при выполнении упражнения можно условно разделить на три вида:

* Ошибки компиляции — это синтаксические ошибки, которые возникают еще на этапе компиляции программы
* Ошибки времени исполнения – такие ошибки не мешают компиляции, но препятствуют выполнению программы
* Ошибки утверждений — ошибки, вызванные тестами. Они возникают, если результат работы функции не соответствует ожидаемому результату

## Ошибки компиляции

Например, к этому типу ошибок относятся:

* Синтаксическая ошибка
* Обращение к несуществующей переменной
* Использование неправильных типов данных

Если программа на Go написана синтаксически некорректно, то компилятор выводит на экран сообщение об ошибке.

Это сообщение выглядит так:

![image](https://github.com/user-attachments/assets/fde4ecf2-7697-4648-9a94-b7d84ace8637)

Сообщение об ошибке содержит:

* Описание ошибки
* Указание на файл, в котором произошла ошибка
* Строчку в файле, где произошла ошибка

## Ошибки времени выполнения

Эти ошибки не препятствуют компиляции, но при этом программа не работает так, как ожидается.

Такие проблемы появляются уже в момент выполнения скомпилированной программы. Возникают различные события, которые нарушают нормальный ход выполнения программы. Эти ошибки не связаны с тестами и сигнализируют о проблеме в коде.

В отличие от других языков, в Go нет исключений — принято возвращать ошибки явно. Но компилятор может анализировать программу во время выполнения и сигнализировать о фатальных ошибках. Например, если программа зависает в ситуации deadlock’a.

Вывод такой ошибки будет выглядеть как:

![image](https://github.com/user-attachments/assets/f249dc34-d7c1-42f0-b253-661cfc52be98)

Если описания недостаточно, всегда можно обратиться к документации, в которой описаны случаи возникновения тех или иных ошибок.

## Ошибки утверждений

Такие ошибки возникают, если результат работы функции не соответствует тому результату, который мы ожидали.

Для начала разберемся, как выглядят тесты для упражнений:

![image](https://github.com/user-attachments/assets/dc8c58a5-a23a-4e2d-84d0-b00e41b0c073)

Тестируемая функция `SafeWrite()`  вызывается в тестах с определенными параметрами. Результат работы функции сравнивается с заранее определенным ожидаемым результатом.

Если фактический и ожидаемый результат совпадают, то все хорошо, тесты пройдены.

Рассмотрим подробнее вывод на вкладке OUTPUT в случае падения тестов:

![image](https://github.com/user-attachments/assets/a6f0bcb3-23f9-4c7d-88a5-d4e02269f34c)

Здесь мы видим:

* Файл с тестами — `main_test.go`
* Номер строки с непройденным тестом — `main_test.go:16`
* Имя самого теста, который не прошел — `Test: TestSafeWrite`
* Ожидаемый результат работы — в строчке `expected`
* Фактический результат работы кода — в строчке `actual`

Изучив такой вывод, мы можем разобраться, чем вызвано несовпадение результатов. Это поможет устранить причину неправильной работы тестируемого кода.

# Отладка кода

Иногда с первого взгляда невозможно понять, чем вызвано неправильное поведение кода. Тогда на помощь приходит отладка — возможность заглянуть в процесс выполнения кода.

Существует несколько способов, но мы рассмотрим самый простой и распространенный — отладочную печать.

Отладочная печать — это вывод на экран значений переменных, вызовов функций, сообщений о выполнении итерации цикла в процессе работы программы.

Для этого достаточно добавить вызов функции `fmt.Println()`  с интересующим нас значением:

![image](https://github.com/user-attachments/assets/338f483c-bfea-40bc-83f7-eb95e94b5c1d)

Затем нужно запустить проверку тестами еще раз, чтобы на вкладке OUTPUT увидеть результат работы нашей отладочной печати:

![image](https://github.com/user-attachments/assets/2c96875b-95cb-4585-af29-1dd3ce39702f)

С помощью отладочной печати мы можем проследить выполнение программы и выяснить, куда закралась ошибка.
